name: ci

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Intall Dependensies
        run: npm ci
        
      - name: Build Project
        run: npm run build

      - name: Deploy to Google App Engine
        uses: claudiuri/deploy-gae-action@master
        with:
          service-account:  ${{ secrets.APP_ENGINE_SERVICE_ACCOUNT }}
          project-id: ${{ secrets.PROJECT_ID }}
